# Generated by Django 5.2.4 on 2025-07-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approval_notification_seen_by_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='approval_notification_viewed_at_by_seller',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
