# Generated by Django 5.2.4 on 2025-07-16 09:16

import django.db.models.deletion
import seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_approval_notification_seen_by_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='registrationNumber',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='shopLogo',
            field=models.ImageField(blank=True, null=True, upload_to=seller.models.shop_logo_upload_path),
        ),
        migrations.CreateModel(
            name='SellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=seller.models.shop_document_upload_path)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seller.seller')),
            ],
        ),
    ]
