# Generated by Django 5.2.4 on 2025-07-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_cancel_reason_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
