# Generated by Django 5.2.4 on 2025-07-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_notified_seller_notified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='registrationNumber',
        ),
    ]
