# Generated by Django 5.2.4 on 2025-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0004_booking_created_at_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
