# Generated by Django 5.2.4 on 2025-07-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0005_booking_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='delivery_charge',
        ),
    ]
