# Generated by Django 5.2.4 on 2025-07-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0007_booking_delivery_address_booking_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
