# Generated by Django 5.2.4 on 2025-07-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0010_notification_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
