# Generated by Django 5.2.4 on 2025-09-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0012_rental_delivery_address_rental_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
