# Generated by Django 5.2.4 on 2025-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0014_auto_20250907_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rented', 'Rented')], default='pending', max_length=10),
        ),
    ]
