# Generated by Django 5.2.4 on 2025-09-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0015_rental_order_id_alter_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='order_id',
        ),
    ]
