# Generated by Django 5.2.4 on 2025-09-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0016_remove_rental_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='extend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
