# Generated by Django 5.2.4 on 2025-09-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0017_rental_extend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='esewa_ref_id',
            field=models.CharField(blank=True, help_text='Reference ID returned by eSewa after successful payment.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='esewa_response_message',
            field=models.TextField(blank=True, help_text='Raw response or error message received from eSewa.', null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='esewa_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', help_text='Current status of the eSewa transaction.', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='esewa_transaction_uuid',
            field=models.CharField(blank=True, help_text='Unique transaction ID sent to eSewa (pid).', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rented', 'Rented'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
