# Generated by Django 5.2.4 on 2025-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kishan', '0019_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolreview',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
